spring:
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      ddl-auto: validate
#    properties:
#      hibernate.format_sql: true
#    show-sql: true
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/master?serverTimezone=Asia/Seoul
      username: root
      password: 'xcz119'
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/slave?serverTimezone=Asia/Seoul
      username: root
      password: 'xcz119'
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000
      connection-timeout: 30000


